[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
tokio-tungstenite = "0.21.0"
game-logic = { path = "../game-logic" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
